apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "frontend-onboarding-demo"
  namespace: "detsombetyrnoe"
  labels:
    "team": "detsombetyrnoe"
spec:
  image: {{ image }} 
  port: 3000
  liveness:
    path: "/api/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/api/isAlive"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi
  ingresses:
    - https://frontend-onboarding-demo.ekstern.dev.nav.no