import Head from "next/head";
import { Heading, Button } from "@navikt/ds-react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading level="1" size="xlarge" spacing>
          Fruktapp
        </Heading>
        <Button variant="primary">Legg til frukt</Button>
      </main>
    </>
  );
}
